### ISSUE TITLE
The two function name are inconsistent

### ISSUE THREAD

**Issue by tu6ge** [jedisct1/rust-minisign#24]
https://github.com/jedisct1/rust-minisign/blob/6f41d0336b28e407e4dae56838142d035e5784da/src/helpers.rs#L4-L11

I am trying run it in wasm, and return :

```
error[E0425]: cannot find function `prompt_password` in this scope
  --> C:\Users\77236\.cargo\registry\src\github.com-1ecc6299db9ec823\minisign-0.7.1\src\helpers.rs:77:15
   |
77 |     let pwd = prompt_password(prompt)?;
   |               ^^^^^^^^^^^^^^^ not found in this scope
```

**Comment by jedisct1** [comment]
Ah, good catch.

They used to be consistent, but Rust being Rust, APIs constantly break in dependencies.

That should be fixed, thanks!
