### ISSUE TITLE
Verification fails when using the `KeyPair` returned by `generate_encrypted_keypair`

### ISSUE THREAD

**Issue by Laegluin** [jedisct1/rust-minisign#3]
When using the key pair struct returned by `KeyPair::generate_encrypted_keypair` to create a signature, verification using the public key fails with `PError { kind: Verify, err: "Could not verify signature with the provided public key ID: 2265E6986983A09D" }`.

When converting the secret key to a string and then loading it again first, signature creation and validation works as expected.

See this gist for short example:
<https://gist.github.com/Laegluin/b07abe10bfabb01b16903c9e1b5aef50>

**Comment by jedisct1** [comment]
The reason is that the keypair is encrypted. All traces of the original secret key are wiped from memory. Signing is not possible without the password.

Instead of `generate_encrypted_keypair()`, you can use `generate_unencrypted_keypair()` to create a password-less key pair, that can be immediately used.

**Comment by jedisct1** [comment]
Granted, the fact that both functions return the same structure is a bit confusing. Maybe different types should be used.

**Comment by Laegluin** [comment]
Thanks a lot, I expected there was a reason I just didn't see.

> Granted, the fact that both functions return the same structure is a bit confusing. Maybe different types should be used.

Yeah, that would be really helpful. I assume that's not a whole lot of work, but I'll gladly help if you need it :)

**Comment by rbauduin** [comment]
Just wanted to confirm it is very confusing.
I've begun using rust recently, and thought I was doing something wrong so I spent a day debugging it, then preparing a demo to post in an issue, but then decided to look at closed issue to find this.  😬
I guess I won't be the last to get this surprise ;-)
This is with version 0.7.9.
