### ISSUE TITLE
Consider renaming "pk" to "pubkey" everywhere

### ISSUE THREAD

**Issue by joshtriplett** [jedisct1/rust-minisign#4]
The abbreviation "pk" seems error-prone; it could abbreviate either "public key" or "private key". Does it seem reasonable to consider expanding it to something like "pubkey" instead?

I'd be happy to provide a patch for this, but I wanted to file an issue for discussion first.

**Comment by jedisct1** [comment]
Hi Josh,

Without any context, `pk` may be confusing, but used in conjunction with `sk`, it's probably okay to keep it that way rather than introducing a breaking change.
