### ISSUE TITLE
Signature verification on prehashed files doesn't work

### ISSUE THREAD

**Issue by Roguelazer** [jedisct1/rust-minisign#6]
It appears that signature verification when prehashing in use doesn't work. Every verification fails with "Signature verification failed".

I wrote the following trivial demo program which takes a pubkey and path on argv and attempts to verify it:
```rust
use std::fs::File;
use std::io::Read;

fn main() {
    let mut args = std::env::args();
    args.next();
    let public_key = args.next().unwrap();
    let path = args.next().unwrap();

    println!("public key is {:?}", public_key);

    let pk = minisign::PublicKey::from_base64(&public_key).unwrap();

    let mut sig_path = path.clone();
    sig_path.push_str(".minisig");

    let mut sig_file = File::open(sig_path).unwrap();

    let mut signature = Vec::new();
    sig_file.read_to_end(&mut signature).unwrap();
    let signature =
        minisign::SignatureBox::from_string(String::from_utf8_lossy(&signature).as_ref()).unwrap();

    let mut f = File::open(path).unwrap();

    println!(
        "verify? {:?}",
        minisign::verify(&pk, &signature, &mut f, true, false)
    );
}
```

If you sign the file with `minisign -S -m /path/to/file`, it verifies fine. If you sign it with `minisign -S -H -m /path/to/file`, verification fails every time. I'm not familiar enough with libsodium to explain away the differences between the Rust and C implementations.

**Comment by Roguelazer** [comment]
I was a little skeptical of your checked-in hand-rolled blake2 implementation, so I swapped it out for the `blake2` crate, but I still get the same hash (which doesn't match the hash from libsodium). I wonder if libsodium is doing something other than bare Blake2b in `crypto_generichash`? Are there any other implementations that support prehashing and don't use libsodium?

**Comment by jedisct1** [comment]
Thanks!

The file was just not loaded correctly. This is been fixed: https://github.com/jedisct1/rust-minisign/commit/29c28fbd1afc0257e464ffac85d0811f151ef6a0

If you only need verification, you can use the [https://docs.rs/minisign-verify](minisign-verify) crate, that is very small, only does verification, and supports prehashing.

I'm going to release a new version of that crate and `rsign2` quickly.

Thanks again!

**Comment by jedisct1** [comment]
The new crate has been published.
